version: '3.8'

services:
  # Spring Boot API服务
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: play-spring-boot-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - app-network
    restart: unless-stopped

  # React前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: play-react-frontend
    ports:
      - "3000:80"
    depends_on:
      api:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  # 如果需要持久化数据，可以添加卷
  app-data:
    driver: local