version: '3.8'

services:
  # Spring Boot API 服务
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: play-spring-boot-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=h2
      - SERVER_PORT=8080
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

  # React 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: play-react-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8080
      - NODE_ENV=production
    depends_on:
      api:
        condition: service_healthy
    networks:
      - app-network

  # Nginx 反向代理 (可选)
  nginx:
    image: nginx:alpine
    container_name: play-nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - frontend
    networks:
      - app-network
    profiles:
      - with-proxy

networks:
  app-network:
    driver: bridge

volumes:
  logs:
    driver: local