version: '3.8'

services:
  # MongoDB 数据库
  mongodb:
    image: mongo:7.0
    container_name: openrtb-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: openrtb
    volumes:
      - mongodb_data:/data/db
      - ./mongodb-init.js:/docker-entrypoint-initdb.d/mongodb-init.js:ro
    networks:
      - openrtb-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis 缓存
  redis:
    image: redis:7.2-alpine
    container_name: openrtb-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass redis123
    volumes:
      - redis_data:/data
    networks:
      - openrtb-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # MongoDB Express (可选的Web管理界面)
  mongo-express:
    image: mongo-express:1.0.0
    container_name: openrtb-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - openrtb-network

  # Redis Commander (可选的Redis管理界面)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: openrtb-redis-commander
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      REDIS_HOSTS: local:redis:6379:0:redis123
      HTTP_USER: admin
      HTTP_PASSWORD: admin123
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - openrtb-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  openrtb-network:
    driver: bridge

# 使用说明:
# 1. 启动所有服务: docker-compose -f docker-compose-openrtb.yml up -d
# 2. 仅启动数据库: docker-compose -f docker-compose-openrtb.yml up -d mongodb redis
# 3. 查看日志: docker-compose -f docker-compose-openrtb.yml logs -f
# 4. 停止服务: docker-compose -f docker-compose-openrtb.yml down
# 5. 清理数据: docker-compose -f docker-compose-openrtb.yml down -v
#
# 访问地址:
# - MongoDB: mongodb://admin:password123@localhost:27017/openrtb
# - Redis: redis://localhost:6379 (密码: redis123)
# - Mongo Express: http://localhost:8081 (用户名/密码: admin/admin123)
# - Redis Commander: http://localhost:8082 (用户名/密码: admin/admin123)