name: E2E Tests (Standalone)

on:
  # 手动触发或特定标签触发
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  # 可以通过workflow_call被其他workflow调用
  workflow_call:

jobs:
  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    services:
      # 如果需要数据库服务，可以在这里添加
      # postgres:
      #   image: postgres:13
      #   env:
      #     POSTGRES_PASSWORD: postgres
      #   options: >-
      #     --health-cmd pg_isready
      #     --health-interval 10s
      #     --health-timeout 5s
      #     --health-retries 5
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci
    
    - name: Install Playwright Browsers
      working-directory: ./frontend
      run: npx playwright install --with-deps
    
    - name: Build frontend
      working-directory: ./frontend
      run: npm run build
    
    - name: Build backend JAR
      run: |
        ./mvnw clean package -DskipTests
        echo "Backend JAR built successfully"
    
    - name: Start backend server
      run: |
        java -jar target/*.jar &
        echo $! > backend.pid
        # 等待后端服务启动
        timeout 120 bash -c 'until curl -f http://localhost:8080/actuator/health 2>/dev/null; do echo "Waiting for backend..."; sleep 5; done'
        echo "Backend server started successfully"
    
    - name: Start frontend server
      working-directory: ./frontend
      run: |
        npm start &
        echo $! > frontend.pid
        # 等待前端服务启动
        timeout 120 bash -c 'until curl -f http://localhost:3000 2>/dev/null; do sleep 2; done'
    
    - name: Run Playwright tests
      working-directory: ./frontend
      run: npm run test:e2e
    
    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: frontend/playwright-report/
        retention-days: 30
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: frontend/test-results/
        retention-days: 30
    
    - name: Stop servers
      if: always()
      run: |
        if [ -f backend.pid ]; then
          kill $(cat backend.pid) || true
        fi
        if [ -f frontend/frontend.pid ]; then
          kill $(cat frontend/frontend.pid) || true
        fi